---
- name: Install k3s on Rocky Linux
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - curl

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -
