---
- name: Fetch the kube configuration from the server for the current user
  hosts: fafnir
  tasks:
  - name: Create directory .kube
    file:
      path: ~{{ ansible_user }}/.kube
      state: directory
      owner: "{{ ansible_user }}"
      mode: "u=rwx,g=rx,o="
    delegate_to: localhost

  - name: Copy config file to user home directory
    become: yes
    fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: ~/.kube/config
      mode: "u=rw,g=,o="
      flat: yes