---
- name: Base provision playbook for all Rocky Linux Servers
  hosts: all
  become: yes

  tasks:
  - name: Ensure all packages are up-to-date.
    dnf:
      name: "*"
      state: latest
     
  - name: Install required dnf packages.
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - chrony
      - cockpit
      - python3-pip
      - nano

  - name: Install required python packages using pip.
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - bpytop

  - name: Ensure services are running.
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - chronyd
      - cockpit.socket